import {
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";
import { basename } from "path/posix";
import { stringify } from "csv-stringify/sync";
import { createHtmlReport } from "./create-html-report";
import type { StepsS3CopyInvokeArguments } from "../../src/steps-s3-copy-input";
import { buildS3Client } from "../common/s3-client-builder";
import { assertInvokeArgumentString } from "../common/assert-invoke-arguments";
import { PRICING_DATA_FILENAME } from "../common/constants";
import { readPricingDataJsonFromS3 } from "../common/cost-estimation";
import type { PricingData } from "../common/cost-estimation";

interface MapResult {
  manifestBucket: string;
  manifestKey: string;
}

interface InvokeEvent {
  invokeArguments: StepsS3CopyInvokeArguments;
  invokeSettings: {
    workingBucket: string;
    workingBucketPrefix: string;
    instructionsPrefix: string;
  };
  rcloneResultsLarge: MapResult;
  rcloneResultsSmall: MapResult;
  rcloneResultsNeedThawSmall: MapResult;
  rcloneResultsNeedThawLarge: MapResult;
  inputCopySets: {
    small: { bucket: string; key: string };
    large: { bucket: string; key: string };
    smallThaw: { bucket: string; key: string };
    largeThaw: { bucket: string; key: string };
  };
}

type TransferStatus = "ERROR" | "ALREADYCOPIED" | "COPIED" | "ESTIMATED";

interface costEstimate {
  crossRegionCostUSD: number;
  coldStorageRetrievalCostUSD: number;
  computeCostUSD: number;
}

export interface FileCopySetsMetadata {
  name: string;
  size: number;
  costEstimate: costEstimate;
}
export interface FileCopyResultMetadata {
  name: string;
  status: TransferStatus;
  speed: number;
  message: string | number;
  destination: string;
  bytesTransferred: number;
  elapsedSeconds: number;
  // source: string;
  // copyMode: string;
}

export interface ReportMetadata {
  copySetsMetadata: FileCopySetsMetadata;
  copyResultMetadata: FileCopyResultMetadata;
}

/**
 * A handler that process the Steps CSV result (which should have a bunch
 * of rclone stats) - and converts that into a CSV report for the
 * copy out destination.
 *
 * @param event
 */
export async function handler(event: InvokeEvent) {
  // debug input event
  console.debug(JSON.stringify(event, null, 2));

  assertInvokeArgumentString(
    event.invokeArguments.destinationPrefix,
    "destinationPrefix",
  );
  assertInvokeArgumentString(
    event.invokeArguments.summaryCsvKey,
    "summaryCsvKey",
  );
  assertInvokeArgumentString(
    event.invokeArguments.htmlReportKey,
    "htmlReportKey",
  );

  // For the working bucket, no bucket definitions are required.
  const workingClient = await buildS3Client();
  // Need to account for bucket definitions for the destination bucket.
  const destClient = await buildS3Client(
    event.invokeArguments.destinationBucket,
    event.invokeArguments.bucketDefinitions,
  );

  // Determine if we need to generate and store the HTML report(s)

  // Read the the copy sets metadata from head object info for the small/large/needThawSmall/needThawLarge
  // that were generated by and stored in S3 as JSONL files in the head-objects-lambda.

  const copySetsKeys = [
    event.inputCopySets.small.key,
    event.inputCopySets.large.key,
    event.inputCopySets.smallThaw.key,
    event.inputCopySets.largeThaw.key,
  ];

  const fileCopySetsMetadata = await readFileCopySetsFromJsonl(
    workingClient,
    event.invokeSettings.workingBucket,
    copySetsKeys,
  );

  // Read the copy results from the manifest files generated by the Distributed Map runs.
  let fileCopyResults: Record<string, FileCopyResultMetadata>;

  if (event.invokeArguments.dryRun) {
    // In a dry run, there is not real copy so produce default/empty
    // FileCopyResultMetadata for all names in fileCopySetsMetadata
    fileCopyResults = {};
    for (const name of Object.keys(fileCopySetsMetadata)) {
      fileCopyResults[name] = {
        name,
        status: "ESTIMATED",
        speed: 0,
        message: "Dry run: no copy performed",
        destination: "",
        bytesTransferred: 0,
        elapsedSeconds: 0,
      };
    }
  } else {
    //  Actual COPY scanario

    // We read and merge the copy manifests from all four maps to get the complete set of copy results.
    const manifestKeys = [
      event.rcloneResultsLarge.manifestKey,
      event.rcloneResultsSmall.manifestKey,
      event.rcloneResultsNeedThawSmall.manifestKey,
      event.rcloneResultsNeedThawLarge.manifestKey,
    ];

    // Read and collate the copy results from the manifest result files, to get a complete set of copy results for all files.
    fileCopyResults = await readFileCopyResultsFromManifests(
      workingClient,
      event.invokeSettings.workingBucket,
      manifestKeys,
    );

    // debug results before we createting files
    console.debug(JSON.stringify(fileCopyResults, null, 2));
  }

  // --------------------------------------------------
  // CVS ended copy generation and storage
  // --------------------------------------------------
  const output = stringify(Object.values(fileCopyResults), {
    header: true,
    columns: {
      name: "OBJECTNAME",
      status: "TRANSFERSTATUS",
      speed: "MBPERSEC",
      message: "MESSAGE",
      destination: "DESTINATION",
      bytesTransferred: "BYTESTRANSFERRED",
      elapsedSeconds: "ELAPSEDSECONDS",
      // source: "SOURCE",
      // copyMode: "COPYMODE",
    },
  });

  // Write the CSV ended copy to the destination S3 bucket/folder
  const csvKey = `${event.invokeArguments.destinationPrefix}${event.invokeArguments.summaryCsvKey}`;
  const putCommand = new PutObjectCommand({
    Bucket: event.invokeArguments.destinationBucket,
    Key: csvKey,
    Body: output,
  });

  // --------------------------------------------------
  // HTML ended copy report generation and storage
  // --------------------------------------------------

  // Prefix in the working bucket where the copy-instructions JSONL lives. Used as the destination
  // for any retained CSV or HTML report.
  const sourceFilePrefix =
    event.invokeSettings.workingBucketPrefix +
    event.invokeArguments.instructionsPrefix;

  // Outputs
  let htmlKey: string | undefined = undefined;
  let workingCsvKey: string | undefined = undefined;
  let workingHtmlKey: string | undefined = undefined;

  if (
    event.invokeArguments.htmlReport ||
    event.invokeArguments.retainHtmlReport
  ) {
    // Prepare metadata for the HTML report generation
    const reportMetadata = Object.keys(fileCopyResults).map((name) => ({
      copySetsMetadata: fileCopySetsMetadata[name]!,
      copyResultMetadata: fileCopyResults[name]!,
    }));

    // Generate the HTML report

    // Read Pricing Data fetcheched from the API
    const pricingDataKey = sourceFilePrefix + PRICING_DATA_FILENAME;

    const pricingData: PricingData = await readPricingDataJsonFromS3(
      workingClient,
      event.invokeSettings.workingBucket,
      pricingDataKey,
    );

    const htmlReport = await createHtmlReport({
      title: "Copy Summary Report",
      destinationBucket: event.invokeArguments.destinationBucket,
      destinationFolderKey: event.invokeArguments.destinationPrefix,
      reportMetadata: reportMetadata,
      dryRun: event.invokeArguments.dryRun ? true : false,
      pricingData: pricingData,
    });

    // 1) Copy to the destination bucket/folder
    if (event.invokeArguments.htmlReport) {
      htmlKey =
        event.invokeArguments.destinationPrefix +
        event.invokeArguments.htmlReportKey;

      await destClient.send(
        new PutObjectCommand({
          Bucket: event.invokeArguments.destinationBucket,
          Key: htmlKey,
          Body: htmlReport,
          ContentType: "text/html; charset=utf-8",
        }),
      );
    }
    // 2) Extra copy to a specific S3 URI (sender retention)
    if (event.invokeArguments.retainHtmlReport) {
      workingHtmlKey = sourceFilePrefix + event.invokeArguments.htmlReportKey;

      await workingClient.send(
        new PutObjectCommand({
          Bucket: event.invokeSettings.workingBucket,
          Key: workingHtmlKey,
          Body: htmlReport,
          ContentType: "text/html; charset=utf-8",
        }),
      );
    }
  }

  await destClient.send(putCommand);

  if (event.invokeArguments.retainSummaryCsv) {
    workingCsvKey = sourceFilePrefix + event.invokeArguments.summaryCsvKey;
    await workingClient.send(
      new PutObjectCommand({
        Bucket: event.invokeSettings.workingBucket,
        Key: workingCsvKey,
        Body: output,
      }),
    );
  }

  return {
    destinationBucket: event.invokeArguments.destinationBucket,
    workingBucket: event.invokeSettings.workingBucket,
    csvKey,
    htmlKey,
    workingCsvKey,
    workingHtmlKey,
  };
}

/**
 * Reads a JSONL file from S3 containing head object info and cost estimates,
 * and returns an array of FilecopySetsMetadata.
 */
export async function readFileCopySetsFromJsonl(
  client: S3Client,
  workingBucket: string,
  copySetsKeys: string[],
): Promise<Record<string, FileCopySetsMetadata>> {
  const fileCopySets: Record<string, FileCopySetsMetadata> = {};
  for (const key of copySetsKeys) {
    const getObjectResult = await client.send(
      new GetObjectCommand({ Bucket: workingBucket, Key: key }),
    );
    if (!getObjectResult.Body) {
      throw new Error("S3 object Body is undefined");
    }
    const content = await getObjectResult.Body.transformToString();
    const lines = content.split(/\r?\n/).filter((l) => l.trim());
    for (const line of lines) {
      const obj = JSON.parse(line);
      const name = basename(obj.destinationKey);
      fileCopySets[name] = {
        name,
        size: obj.size,
        costEstimate: obj.costEstimate,
      };
    }
  }
  return fileCopySets;
}

async function readFileCopyResultsFromManifests(
  client: S3Client,
  workingBucket: string,
  manifestKeys: string[],
): Promise<Record<string, FileCopyResultMetadata>> {
  // Each Distributed Map we run (Large, Small, NeedThawSmall, NeedThawLarge) writes a
  // `manifest.json` to S3. The manifest is generated by Step Functions and summarises the
  // per-item copy result files for that map run (grouped into PENDING / FAILED / SUCCEEDED).
  //
  // Example:
  // {"DestinationBucket":"elsa-data-tmp",
  // "MapRunArn":"arn:aws:states:ap-southeast-2:12345678:mapRun:CopyOutStateMachineABCD/4474d22f-4056-30e3-978c-027016edac90:0c17ffd6-e8ad-44c0-a65b-a8b721007241",
  // "ResultFiles":{
  //     "FAILED":[],
  //     "PENDING":[],
  //     "SUCCEEDED":[{"Key":"copy-out-test-working/a6faea86c066cd90/1-objects-to-copy.tsv/0c17ffd6-e8ad-44c0-a65b-a8b721007241/SUCCEEDED_0.json",
  //                   "Size":2887}]}}

  // Arrays to hold the result file keys from all manifests.
  const pendingFiles: any[] = [];
  const failedFiles: any[] = [];
  const succeededFiles: any[] = [];

  // Iterate over all the manifest key produced by each map.
  for (const manifestKey of manifestKeys) {
    const getManifestCommand = new GetObjectCommand({
      Bucket: workingBucket,
      Key: manifestKey,
    });

    const getManifestResult = await client.send(getManifestCommand);
    if (!getManifestResult.Body) {
      throw new Error("Manifest S3 object Body is undefined");
    }

    const getManifestContent = await getManifestResult.Body.transformToString();

    const manifest = JSON.parse(getManifestContent);

    console.debug(JSON.stringify(manifest, null, 2));

    const resultFiles = manifest["ResultFiles"];

    if (!resultFiles)
      throw new Error(
        "AWS Steps Distributed map manifest.json is missing ResultFiles",
      );

    pendingFiles.push(...resultFiles["PENDING"]);
    failedFiles.push(...resultFiles["FAILED"]);
    succeededFiles.push(...resultFiles["SUCCEEDED"]);
  }

  // Validate manifest shape: all three status buckets must be arrays.
  if (
    !Array.isArray(pendingFiles) ||
    !Array.isArray(failedFiles) ||
    !Array.isArray(succeededFiles)
  )
    throw new Error(
      "AWS Steps Distributed map manifest.json is missing an expected array for PENDING, FAILED or SUCCEEDED",
    );

  // Fail if PENDING.
  // By the time this Lambda runs,
  // the Distributed Map should have fully completed (no partial results).
  if (pendingFiles.length > 0)
    throw new Error(
      "AWS Steps Distributed map manifest.json indicates there are PENDING results which is not a state we are expecting",
    );

  // Fail if FAILED.
  // This Lambda is only expected to be run when the copy has fully succeeded.
  // Maybe in future we want to handle partial success.
  if (failedFiles.length > 0)
    throw new Error("Copy is meant to succeed - but it had failed results");

  // Process each SUCCEEDED result file to extract stats.

  // fileCopyResults will hold the final collated results for all files.
  const fileCopyResults: Record<string, FileCopyResultMetadata> = {};

  for (const succeededFile of succeededFiles) {
    const getSuccessCommand = new GetObjectCommand({
      Bucket: workingBucket,
      Key: succeededFile["Key"],
    });

    const getSuccessResult = await client.send(getSuccessCommand);
    if (!getSuccessResult.Body) {
      throw new Error("Success S3 object Body is undefined");
    }

    const getSuccessContent = await getSuccessResult.Body.transformToString();

    const content = getSuccessContent.trim();
    const rows = content.startsWith("[")
      ? JSON.parse(content)
      : JSON.parse(
          `[${content
            .split(/\r?\n/)
            .filter((l) => l.trim())
            .join(",")}]`,
        );

    // Each row in the result file corresponds to a single file copy attempt and contains rclone stats.
    for (const row of rows) {
      // NOTE/WARNING: this behaviour is very dependent on rclone and our interpretation
      // of rclone stats - so if things start breaking this is where I would start
      // looking

      const source = row["source"];
      // The name is the basename of the source.

      // Original values
      // const errors: number = rcloneRow["errors"];
      // const lastError: number = rcloneRow["lastError"];
      // const serverSideCopyBytes: number = rcloneRow["serverSideCopyBytes"];
      // const elapsedTime = rcloneRow["elapsedTime"];
      // const totalTransfers = rcloneRow["totalTransfers"];
      // const retryError = rcloneRow["retryError"];

      // Debbuged

      // Is there were any errors during the transfer ?
      const errors: number = row["errors"] ?? 0;

      const name = basename(source);

      // Compute the transfer speed
      const elapsedSeconds = row["elapsedSeconds"] ?? 0;
      const bytesTransferred = row["bytesTransferred"] ?? 0;
      const speedMiBps =
        elapsedSeconds > 0
          ? bytesTransferred / elapsedSeconds / 1024 / 1024
          : 0;

      const destination = row["destination"];
      const lastError: number = row["lastError"];
      const retryError = row["retryError"]; // Not being passed

      // if we have been signalled an error - we need to report that
      if (errors > 0) {
        fileCopyResults[name] = {
          name: name,
          status: "ERROR",
          speed: speedMiBps,
          message: lastError,
          destination: destination,
          bytesTransferred: bytesTransferred,
          elapsedSeconds: elapsedSeconds,
        };
      } else {
        // if we didn't end up transferring anything BUT there was no actual error AND
        // we did a retry - then that probably means the source file didn't exist
        if (bytesTransferred < 1 && retryError) {
          fileCopyResults[name] = {
            name: name,
            status: "ERROR",
            speed: speedMiBps,
            message: "source file did not exist so nothing was transferred",
            destination: destination,
            bytesTransferred: bytesTransferred,
            elapsedSeconds: elapsedSeconds,
          };
        }
        // if we didn't end up transferring anything BUT there was no actual error
        // AND we didn't do any retries then changes are we skipped due to it already
        // being at the destination
        else if (bytesTransferred < 1 && !retryError) {
          fileCopyResults[name] = {
            name: name,
            status: "ALREADYCOPIED",
            speed: speedMiBps,
            message:
              "destination file already exists with same checksum so nothing was transferred",
            destination: destination,
            bytesTransferred: bytesTransferred,
            elapsedSeconds: elapsedSeconds,
          };
        } else {
          fileCopyResults[name] = {
            name: name,
            status: "COPIED",
            speed: speedMiBps,
            message: "",
            destination: destination,
            bytesTransferred: bytesTransferred,
            elapsedSeconds: elapsedSeconds,
          };
        }
      }
    }
  }

  return fileCopyResults;
}
