name: Release Package

on:
  release:
    types: [released]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish-to-npm-registry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - run: bun install

      # first set the version tag of our package to the release version

      - run: npm version ${{github.ref_name}}
        working-directory: packages/steps-s3-copy

      # build and package

      - run: bun run build

      - run: bun run package

      # if all the builds have completed - we can publish the package
      # publib-npm needs newest NPM 11 to have trusted publisher mode.
      # Currently node 22.22.2 has a broken npm, so use corepack directly.
      - run: corepack enable npm
      - run: corepack install -g npm@11

      - run: bunx publib-npm
        working-directory: packages/steps-s3-copy
        env:
          NPM_TRUSTED_PUBLISHER: true
          NPM_ACCESS_LEVEL: public
          # Required for global corepack npm installation
          COREPACK_ENABLE_STRICT: 0
